#!/usr/bin/env bash
# a bash script that displays:
# To infinity and beyond indefinitely
# with a sleep 2 in between each iteration
# I am invincible!!! when receiving SIGTERM signal

msg="I am invincible!!!"

trap 'echo $msg' SIGTERM

while true
do
	echo "To infinity and beyond"
	sleep 2
done
