#!/usr/bin/env bash
# A bash script that displays Best School
# But on the 9th iteration displays Hi on new line


i=1

while [ $i -le 10 ]
do
	echo "Best School"
	if [ $i -eq 9 ]
	then
		echo "Hi"
	fi
	i=$((i + 1))
done
