#!/usr/bin/env bash
# Bash script that displays
# The content of the current directory
# in list format
# Where only the part of the name after the first dash is displayed

directory=$(ls)

for i in $directory
do
	echo "$i" | cut -d '-' -f2
done
