#!/usr/bin/env bash
# Configures an Ubuntu server with the below requirements
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/hosts.new
printf "127.0.0.2\tlocalhost\n" > ~/hosts.new
printf "8.8.8.8\tfacebook.com\n" >> ~/hosts.new
cp ~/hosts.new /etc/hosts
